[package]
name = "notabena"
version = "0.0.1-dev"
edition = "2021"
authors = [ "Mart Zielman", "Serge" ]

[dependencies]
async-std = "1.12.0"
chrono = "0.4.23"
inquire = "0.6.2"
rusqlite = { version = "0.29.0", features = ["bundled"] }
