name: CI checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_formatting: 
    runs-on: ubuntu-latest, windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --all -- --check
    
  build:
    runs-on: ubuntu-latest, windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all-features
